### ISSUE TITLE
Remove Some Default Bookmarks

### ISSUE THREAD

**Issue by tobiastromm** [rn10950/RetroZilla#11]
Hi.

By default there is three bookmarks,  but, two of them are Offline, can you remove them to keep browser updated?

They are:
- RetroZilla (http://retrozilla.no-ip.org/ - Info: Address Not Found);
- mozillaZine (http://www.mozillazine.org/ - Info: MozillaZine's news site has gone into hibernation).

Thanks.

**Comment by rn10950** [comment]
I'm going to keep mozillazine for the forums, but I updated the RetroZilla link. However, it will not update for existing profiles.
