### ISSUE TITLE
Modal Alert Dialog

### ISSUE THREAD

**Issue by Azvareth** [rn10950/RetroZilla#20]
Hi... Thanks for working on FileZilla

I Was testing the browser on Windows 98 SE (with all official and unofficial updates possible)

(I am reproducing the exact steps as I am writing this)

When I was testing some Mozilla site (http://www.mozdev.org), I was caught in what seemed to be a recursive call to load a page,  first I got an "Alert Requester" that complained about SSL and browser could not connect to cse.google.com because the SSL protocol has been disabled. (more of that later)

I clicked OK and the page loaded and the requester disappeared, then I selected the second leftmost menu option (Project) on the website. Page tries to load then the requester popped back up with the same message. Now every time I click OK on the requester the page seems to load itself into a new frame (but not exactly) with the same content and the banner (and all content so far) of the page duplicates itself and add itself to the previous content, and the requester continues to popup....

That in itself is quite bad, but I am however asking if you could change the Requester kind when called from the browser with some browser error to be not modal (or an option to close that page with the error and go to the startpage [perhaps with a third option to save the page and scripts as well for further investigation]), as it is now I had to launch process explorer (or use CTRL+ALT+DEL) to terminate RetroZilla... Then fire it up.

Ok sorry for this, it is both a minor issue and a request to add something... Hope you don't mind...

btw: The settings in ...Zilla has the options of SSL ticked...

**Comment by rn10950** [comment]
I will try it out when I get home. I have a feeling that the SSL issue will go away with the update that is going to be released sometime in the coming days/weeks. (I need to fix a build system issue on my PC, don't have a solid ETA yet).

**Comment by rn10950** [comment]
OK, I tested out the page with one of my testing builds with the new SSL improvement, and there is no SSL error. I am going to release that build to the public once I fix a build system error that is preventing certificates from loading properly, documented in the comments of #7. (If you want, I can send you the release with the certificate issue, but it is EXTREMELY annoying. Every single page you load that has an HTTPS request, sometimes 5-6 per page, pops an unknown root certificate error). 

Regarding the whole "in a new frame" thing, that seems to be an issue with the site itself. I tested it out in Pale Moon and the render looks the same as it does in RetroZilla (it also seems to load recursively until the browser can't handle it anymore, it almost brung my PC running a 64-bit browser and OS with 24GB of RAM to a halt) https://i.imgur.com/U0GV7t7.png

**Comment by Azvareth** [comment]
Thanks, I wait for the release. I have waited this far, so I am in no hurry, it is fun to test new things that make a difference, and a browser for Win9x+ is such a thing in my opinion...

Yes!
That image shows exactly what happened to my machine as well
W98
500 MB RAM
trying out RetroZilla

perhaps you somewhere long time in the future like to think about adding user scripts like it (was|is)? in Opera, so it could intercept and modify some bad sites before rendering starts?

//Sincerly Azvareth

**Comment by rn10950** [comment]
> perhaps you somewhere long time in the future like to think about adding user scripts like it (was|is)? in Opera, so it could intercept and modify some bad sites before rendering starts?

User script support will most likely be coming in a future release, along with a "script store" type thing. One thing I realized over time working with RetroZilla is that we could try to add support for new features, but we still won't be 100% compatible with the modern web. I figure a way to *try to* fix that would be to add a user-contributed "patches catalog" that will give users the option to contribute JS and CSS fixes for different sites, and pop up a non-intrusive (and disable-able) dialog when you visit a site that has patches avaliable. I also will look into redirecting all the requests around the web for jQuery and the like, which checks browser versions for compatibility before running, to an internally hosted copy that is the latest version that I could hack into working on our older Gecko platform. This alone will probably fix a lot of the JS and layout issues on the modern web.

**Comment by roytam1** [comment]
> btw, perhaps you should modify your webbrowser recomendation for W98SE on start page to include Opera 12.02 under KernelEx Win2000 SP4 mode.

I think recommending a browser that needs KernelEx is not good here, as KernelEx itself is unstable.
