### ISSUE TITLE
Mozconfig.mk does not rebuild on change of OBJDIR

### ISSUE THREAD

**Issue by rn10950** [rn10950/RetroZilla#23]
On two different systems, a change of the OBJDIR in .mozconfig does not change the objdir in mozconfig.mk, therefore not changing the OBJDIR and building in the old directory. If the OBJDIR is changed manually in mozconfig.mk, the build completes in the specified directory.

**Comment by roytam1** [comment]
does `make -f client.mk configure build` work anyway?
