### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Siphonay** [rn10950/RetroZilla#26]
Hello! I'd like to build the current master branch of RetroZilla. I installed Visual Studio 6 and MozillaBuild 1.2 on Windows 2000 SP4 like you said you did on your website, and cloned the source on there as well, but I'm not sure what to do now. Did I miss obvious build instructions?

Thanks in advance for your help, sorry if this is not the right place to ask, I didn't find any way to contact you from elsewhere

**Comment by rn10950** [comment]
> Thanks in advance for your help, sorry if this is not the right place to ask, I didn't find any way to contact you from elsewhere

No problem.

1. You're going to need to install [VC6 SP5](http://ftp.wsisiz.edu.pl/pub/pc/microsoft/visual%20studio%20professional%206.0/vs6sp5.exe) (not SP6) and [VC6 Processor Pack](http://www.website.masmforum.com/microsoft/vcpp5.exe). If the SP5 executable is not in English, please let me know, I'll look for another one, it can be hard to find these days in English (which is needed for it to install into en-US VC++ properly)

2. Place your source somewhere in a directory without spaces if it's not already. I recommend something like C:\projects\RetroZilla\RetroZilla. 

3. Start "start-msvc6.bat" in C:\mozilla-build\. This will open a UNIX-type shell window. navigate to your source directory. It uses UNIX-style file paths with the Windows drive letters as the first child directory (e.g. C:\WINDOWS\System32 will be /c/WINDOWS/System32 in MSYS shell) 

4. Copy mozconfig-suite.txt to mozconfig (no extension). Open up your newly created mozconfig in a text editor. You're going to want to change the object directory, I recommend changing it to the parent directory of the source. Using my example for a source directory above, change
`mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-sm95-release`
to 
`mk_add_options MOZ_OBJDIR=/c/projects/RetroZilla/obj-rzSuite-release`

4. Now just run `make -f client.mk build_all` from the MSYS shell and wait.

If you experience any issues, please let me know. Please be warned that master is currently suffering from fallout from #7, and I am in the process of working those issues out (root certificates not working).

**Comment by Siphonay** [comment]
It's really nice of you to write such a detailed guide for me. I'll try it out when I can and come back to you if I have any issues. Thanks a lot!

**Comment by Siphonay** [comment]
The SP5 executable worked and was in English, but mozilla-build apparently can't find it
![image](https://user-images.githubusercontent.com/6833300/43224839-cd705b4e-9057-11e8-80e1-cabbfc5ab26c.png)

Is there anything I can do about it?

**Comment by roytam1** [comment]
> Is there anything I can do about it?

do you register environment variable when installing VS6?

**Comment by rn10950** [comment]
build instructions now in readme.md
