### ISSUE TITLE
[Q] Build "Browser-only"

### ISSUE THREAD

**Issue by roytam1** [rn10950/RetroZilla#4]
Is it possible to build a "Browser-only" (Firefox-alike) solution?

**Comment by rn10950** [comment]
The Firefox source is checked in to the GitHub tree, there is an example mozconfig for Firefox, but it is untested. Here is the mozconfig: https://github.com/rn10950/RetroZilla/blob/master/mozconfig-browser.txt. There is, however, a way to install RetroZilla without mailnews and composer. If you grab the win32 installer and choose Custom, you can choose which features to install. Navigator is the browser and the rest is self explanatory.
