### ISSUE TITLE
TLS 1.2 support

### ISSUE THREAD

**Issue by roytam1** [rn10950/RetroZilla#7]
Huge diff and non-staged files, so modified ZIP archive of nsprpub/ , security/manager/ and security/nss/ below(rename from docx to zip for ZIP archive contains 2 7z archive of aforementioned folders)
[RetroZilla.zip](https://github.com/rn10950/RetroZilla/files/1359001/RetroZilla.docx)

and a diff of enabling AES GCM ciphers:
```
diff --git a/netwerk/base/public/security-prefs.js b/netwerk/base/public/security-prefs.js
index 0e17f7b..c98b23a 100644
--- a/netwerk/base/public/security-prefs.js
+++ b/netwerk/base/public/security-prefs.js
@@ -53,6 +53,10 @@ pref("security.ssl3.dhe_dss_des_sha", false);
 pref("security.ssl3.rsa_null_sha", false);
 pref("security.ssl3.rsa_null_md5", false);

+pref("security.ssl3.rsa_seed_sha", true);
+pref("security.ssl3.ecdhe_ecdsa_aes_128_gcm_sha256", true);
+pref("security.ssl3.ecdhe_rsa_aes_128_gcm_sha256", true);
+
 pref("security.default_personal_cert",   "Ask Every Time");
 pref("security.remember_cert_checkbox_default_setting", true);
 pref("security.ask_for_password",        0);
```

**Comment by rn10950** [comment]
Great! Did you try building with this code, did it build successfully? I still have a difficult time of building on the new laptop that I am using for RZ. If this works as intended, I'll ship it in RZ3. Also, if you want, I could add you as a contributor to the project so you could commit to GitHub yourself.

**Comment by roytam1** [comment]
NSPR supplement patch for VC6:

```
diff -rU5 nsprpub/pr/include/private/primpl.h nsprpub_vc6/pr/include/private/primpl.h
--- nsprpub/pr/include/private/primpl.h	2013-11-09 17:49:40.000000000 +0800
+++ nsprpub_vc6/pr/include/private/primpl.h	2017-10-07 11:37:25.000000000 +0800
@@ -23,19 +23,19 @@
 #endif
 
 #ifdef WIN32
 /*
  * Allow use of functions and symbols first defined in Win2k.
- */
+ * /
 #if !defined(WINVER) || (WINVER < 0x0500)
 #undef WINVER
 #define WINVER 0x0500
 #endif
 #if !defined(_WIN32_WINNT) || (_WIN32_WINNT < 0x0500)
 #undef _WIN32_WINNT
 #define _WIN32_WINNT 0x0500
-#endif
+#endif*/
 #endif /* WIN32 */
 
 #include "nspr.h"
 #include "prpriv.h"
 
diff -rU5 nsprpub/pr/src/md/windows/w95cv.c nsprpub_vc6/pr/src/md/windows/w95cv.c
--- nsprpub/pr/src/md/windows/w95cv.c	2013-11-09 17:49:40.000000000 +0800
+++ nsprpub_vc6/pr/src/md/windows/w95cv.c	2017-10-07 11:50:59.718750000 +0800
@@ -309,10 +309,16 @@
     DWORD dwSpinCount,
     DWORD Flags);
 
 static INITIALIZECRITICALSECTIONEX sInitializeCriticalSectionEx;
 
+typedef BOOL (WINAPI *INITIALIZECRITICALSECTIONANDSPINCOUNT)(
+    CRITICAL_SECTION *lpCriticalSection,
+    DWORD dwSpinCount);
+
+static INITIALIZECRITICALSECTIONANDSPINCOUNT sInitializeCriticalSectionAndSpinCount;
+
 void _PR_MD_INIT_LOCKS(void)
 {
     /*
      * Starting with Windows Vista, every CRITICAL_SECTION allocates an extra
      * RTL_CRITICAL_SECTION_DEBUG object. Unfortunately, this debug object is
@@ -324,30 +330,38 @@
     HMODULE hKernel32 = GetModuleHandle("kernel32.dll");
     PR_ASSERT(hKernel32);
     PR_ASSERT(!sInitializeCriticalSectionEx);
     sInitializeCriticalSectionEx = (INITIALIZECRITICALSECTIONEX)
             GetProcAddress(hKernel32, "InitializeCriticalSectionEx");
+    sInitializeCriticalSectionAndSpinCount = (INITIALIZECRITICALSECTIONANDSPINCOUNT)
+            GetProcAddress(hKernel32, "InitializeCriticalSectionAndSpinCount");
 }
 
 /*
  * By default, CRITICAL_SECTIONs are initialized with a spin count of 0.
  * Joe Duffy's "Concurrent Programming on Windows" book suggests 1500 is
  * a "reasonable starting point". On single-processor systems, the spin
  * count is ignored and the critical section spin count is set to 0.
  */
 #define LOCK_SPIN_COUNT 1500
 
+#ifndef CRITICAL_SECTION_NO_DEBUG_INFO
+#define CRITICAL_SECTION_NO_DEBUG_INFO 0x01000000
+#endif
+
 PRStatus _PR_MD_NEW_LOCK(_MDLock *lock)
 {
     CRITICAL_SECTION *cs = &lock->mutex;
     BOOL ok;
 
     if (sInitializeCriticalSectionEx) {
         ok = sInitializeCriticalSectionEx(cs, LOCK_SPIN_COUNT,
                                           CRITICAL_SECTION_NO_DEBUG_INFO);
-    } else {
-        ok = InitializeCriticalSectionAndSpinCount(cs, LOCK_SPIN_COUNT);
+    } else if (sInitializeCriticalSectionAndSpinCount) {
+        ok = sInitializeCriticalSectionAndSpinCount(cs, LOCK_SPIN_COUNT);
+    } else  {
+        ok = 1, InitializeCriticalSection(cs);
     }
     if (!ok) {
         _PR_MD_MAP_DEFAULT_ERROR(GetLastError());
         return PR_FAILURE;
     }
diff -rU5 nsprpub/pr/src/md/windows/w95thred.c nsprpub_vc6/pr/src/md/windows/w95thred.c
--- nsprpub/pr/src/md/windows/w95thred.c	2013-11-09 17:49:40.000000000 +0800
+++ nsprpub_vc6/pr/src/md/windows/w95thred.c	2017-10-07 11:32:03.343750000 +0800
@@ -10,10 +10,11 @@
 /*
  * VC++ 6.0 doesn't have DWORD_PTR.
  */
 
 typedef DWORD DWORD_PTR;
+typedef unsigned long ULONG_PTR;
 #endif /* _MSC_VER <= 1200 */
 
 /* --- globals ------------------------------------------------ */
 #ifdef _PR_USE_STATIC_TLS
 __declspec(thread) struct PRThread  *_pr_thread_last_run;
Only in nsprpub_vc6/pr/src/memory: Makefile
Only in nsprpub_vc6/pr/src/misc: Makefile
diff -rU5 nsprpub/pr/src/misc/prsystem.c nsprpub_vc6/pr/src/misc/prsystem.c
--- nsprpub/pr/src/misc/prsystem.c	2013-11-09 17:49:40.000000000 +0800
+++ nsprpub_vc6/pr/src/misc/prsystem.c	2017-10-07 11:53:54.500000000 +0800
@@ -54,10 +54,28 @@
 #if defined(AIX)
 #include <cf.h>
 #include <sys/cfgodm.h>
 #endif
 
+#if defined(WIN32)
+/* This struct is not present in VC6 headers, so declare it here */
+typedef struct {
+    DWORD dwLength;
+    DWORD dwMemoryLoad;
+    DWORDLONG ullTotalPhys;
+    DWORDLONG ullAvailPhys;
+    DWORDLONG ullToalPageFile;
+    DWORDLONG ullAvailPageFile;
+    DWORDLONG ullTotalVirtual;
+    DWORDLONG ullAvailVirtual;
+    DWORDLONG ullAvailExtendedVirtual;
+} PR_MEMORYSTATUSEX;
+
+/* Typedef for dynamic lookup of GlobalMemoryStatusEx(). */
+typedef BOOL (WINAPI *GlobalMemoryStatusExFn)(PR_MEMORYSTATUSEX *);
+#endif
+
 PR_IMPLEMENT(char) PR_GetDirectorySeparator(void)
 {
     return PR_DIRECTORY_SEPARATOR;
 }  /* PR_GetDirectorySeparator */
 
@@ -307,14 +325,33 @@
     if (result == KERN_SUCCESS)
         bytes = hInfo.max_mem;
 
 #elif defined(WIN32)
 
-    MEMORYSTATUSEX memStat;
-    memStat.dwLength = sizeof(memStat);
-    if (GlobalMemoryStatusEx(&memStat))
-        bytes = memStat.ullTotalPhys;
+    /* Try to use the newer GlobalMemoryStatusEx API for Windows 2000+. */
+    GlobalMemoryStatusExFn globalMemory = (GlobalMemoryStatusExFn) NULL;
+    HMODULE module = GetModuleHandle("kernel32.dll");
+
+    if (module) {
+        globalMemory = (GlobalMemoryStatusExFn)GetProcAddress(module, "GlobalMemoryStatusEx");
+
+        if (globalMemory) {
+            PR_MEMORYSTATUSEX memStat;
+            memStat.dwLength = sizeof(memStat);
+
+            if (globalMemory(&memStat))
+                bytes = memStat.ullTotalPhys;
+        }
+    }
+
+    if (!bytes) {
+        /* Fall back to the older API. */
+        MEMORYSTATUS memStat;
+        memset(&memStat, 0, sizeof(memStat));
+        GlobalMemoryStatus(&memStat);
+        bytes = memStat.dwTotalPhys;
+    }
 
 #elif defined(OS2)
 
     ULONG ulPhysMem;
     DosQuerySysInfo(QSV_TOTPHYSMEM,

```

**Comment by roytam1** [comment]
Second try. Build should pass now.
[RetroZilla-nss-nspr-update.zip](https://github.com/rn10950/RetroZilla/files/1364723/RetroZilla-nss-nspr-update.docx)

**Comment by roytam1** [comment]
This one works in Win95 OSR2 now!
[RetroZilla-nss-nspr-update-20171008.zip](https://github.com/rn10950/RetroZilla/files/1366648/RetroZilla-nss-nspr-update-20171008.docx)

**Comment by roytam1** [comment]
updated UTF8 functions in db\sqlite3\src\os_win.c (supplement of https://github.com/rn10950/RetroZilla/issues/7#issuecomment-334985097 ):

```
int Utf8ToWideChar(unsigned int unused1, unsigned long unused2, char *sb, int ss, wchar_t * wb, int ws) {
  static const unsigned char utf8mask[] = { 0, 0xff, 0x1f, 0x0f, 0x07, 0x03, 0x01 };
  char *p = (char *)(sb);
  char *e = (char *)(sb + ss);
  wchar_t *w = wb;
  int cnt = 0, t, qch;

  if (ss < 1) {
    ss = lstrlenA(sb);
    e = (char *)(sb + ss);
  }

  if (wb && ws) {
    for (; p < e; ++w) {
	  t = utf8GetMaskIndex(*p);
	  qch = (*p++ & utf8mask[t]);
	  while(p < e && --t)
	    qch <<= 6, qch |= (*p++) & 0x3f;
	  if(qch < 0x10000) {
	    if(cnt <= ws)
		  *w = (wchar_t) qch;
	    cnt++;
	  } else {
	    if (cnt + 2 <= ws) {
		  *w++ = (wchar_t) (0xD800 + (((qch - 0x10000) >> 10) & 0x3ff)),
		    *w = (wchar_t) (0xDC00 + (((qch - 0x10000)) & 0x3ff));
		}
	    cnt += 2;
	  }
	}
    return (cnt <= ws) ? cnt : ws;
  } else {
    for (t; p < e;) {
	  t = utf8GetMaskIndex(*p);
	  qch = (*p++ & utf8mask[t]);
	  while (p < e && --t)
	    qch <<= 6, qch |= (*p++) & 0x3f;
	  if (qch < 0x10000)
	    cnt++;
	  else
	    cnt += 2;
	}
    return cnt+1;
  }
}

int WideCharToUtf8(unsigned int unused1, unsigned long unused2, wchar_t * wb, int ws, char *sb, int ss) {
  wchar_t *p = (wchar_t *)(wb);
  wchar_t *e = (wchar_t *)(wb + ws);
  wchar_t *oldp;
  char *s = sb;
  int cnt = 0, qch, t;

  if (ws < 1) {
    ws = lstrlenW(wb);
    e = (wchar_t *)(wb + ws);
  }

  if (sb && ss) {
    for (t; p < e; ++p) {
	  oldp = p;
	  t = wc2Utf8Len(&p, &ws);

	  if (p != oldp) { /* unicode surrogates encountered */
	    qch = 0x10000 + (((*oldp - 0xD800) & 0x3ff) << 10) + ((*p - 0xDC00) & 0x3ff);
	  } else
	    qch = *p;

	  if (qch <= 0x7f)
	    *s++ = (char) (qch),
	    cnt++;
	  else if (qch <= 0x7ff)
	    *s++ = 0xc0 | (char) (qch >> 6),
	    *s++ = 0x80 | (char) (qch & 0x3f),
	    cnt += 2;
	  else if (qch <= 0xffff)
	    *s++ = 0xe0 | (char) (qch >> 12),
	    *s++ = 0x80 | (char) ((qch >> 6) & 0x3f),
	    *s++ = 0x80 | (char) (qch & 0x3f),
	    cnt += 3;
	  else if (qch <= 0x1fffff)
	    *s++ = 0xf0 | (char) (qch >> 18),
	    *s++ = 0x80 | (char) ((qch >> 12) & 0x3f),
	    *s++ = 0x80 | (char) ((qch >> 6) & 0x3f),
	    *s++ = 0x80 | (char) (qch & 0x3f),
	    cnt += 4;
	  else if (qch <= 0x3ffffff)
	    *s++ = 0xf8 | (char) (qch >> 24),
	    *s++ = 0x80 | (char) ((qch >> 18) & 0x3f),
	    *s++ = 0x80 | (char) ((qch >> 12) & 0x3f),
	    *s++ = 0x80 | (char) ((qch >> 6) & 0x3f),
	    *s++ = 0x80 | (char) (qch & 0x3f),
	    cnt += 5;
	  else
	    *s++ = 0xfc | (char) (qch >> 30),
	    *s++ = 0x80 | (char) ((qch >> 24) & 0x3f),
	    *s++ = 0x80 | (char) ((qch >> 18) & 0x3f),
	    *s++ = 0x80 | (char) ((qch >> 12) & 0x3f),
	    *s++ = 0x80 | (char) ((qch >> 6) & 0x3f),
	    *s++ = 0x80 | (char) (qch & 0x3f),
	    cnt += 6;
	}
      return (cnt <= ss) ? cnt : ss;
  } else {
    for (t; p < e; ++p) {
	  t = wc2Utf8Len(&p, &ws);
	  cnt += t;
	}
    return cnt+1;
  }
}

```

**Comment by roytam1** [comment]
finally redone properly:
https://github.com/roytam1/RetroZilla/compare/ba7f53c261b7e706825723380c56b02a6807a0cb...a5a8c74bdd9f518fecf29208b7dd78714bb40ceb

**Comment by rn10950** [comment]
added. #17

**Comment by rn10950** [comment]
You seem to be a little more knowledgeable with NSS than I am. I keep running into cert issues on almost every site. I compared the certdata.txt from both Mozilla's website and the RZ NSS source, and noticed almost zero differences, with the exception of our certdata file having more certificates than the official Mozilla one. I updated Windows' roots, but that makes no difference. If/when we can try to resolve this, I will push yet another stopgap, as the current release also suffers from this CA issue as well.

**Comment by roytam1** [comment]
> with the exception of our certdata file having more certificates than the official Mozilla one

because it comes from NSS 3.36.
you may check built-in cert store in options -> advanced -> security -> view certs -> authorities, if the column is built-in objects then it comes from certdata.txt

**Comment by rn10950** [comment]
My list is actually blank, even in a new profile.

**Comment by roytam1** [comment]
> My list is actually blank, even in a new profile.

then something goes wrong. do you have nssckbi.dll in your folder where gecko dll files lives?

**Comment by rn10950** [comment]
Yes

**Comment by roytam1** [comment]
authorities tab should not be blank, did you try building debug build and see what console window showing about security while running?

**Comment by rn10950** [comment]
I just started a full debug build with the console logging into a text file, I will check on it in the morning. I'm on the US East Coast, so it's almost 4:00 AM here.

**Comment by roytam1** [comment]
compile log should not be a problem(i.e. build should pass), the important thing is runtime console log. lets see how it does.

**Comment by rn10950** [comment]
The Firefox build works fine. It must be an issue getting the suite to recognize the new cert file.

**Comment by roytam1** [comment]
> It must be an issue getting the suite to recognize the new cert file.

then there may be some changes has to be done in suite side, but thats the area I didn't actually touch with.

**Comment by rn10950** [comment]
Do you have a general idea of the changes you had to do to /browser when you upgraded NSS? I'm currently running another logged suite build to check the compile logs. I saw nothing on the debug logs (except *seemingly* unrelated errors that can be fixed later on) Here it is if you want to take a look at it, maybe you will catch something I didn't: https://pastebin.com/DUdv1Pr2

I will examine and post the new compile logs later when they're done. I have an odd feeling that the cert file is not being processed properly during build.

**Comment by roytam1** [comment]
The log doesn't show anything about NSS/SSL/TLS, did you try accessing site with https?

**Comment by rn10950** [comment]
I ran the debug build again while loading a HTTPS site (Google) and captured the log. I accepted each certificate for this session only: https://pastebin.com/2yehNAdB

**Comment by roytam1** [comment]
still can't get logs about pip/nss, try appending `-DFORCE_PR_LOG -DPR_LOGGING=1`  in : 
https://github.com/rn10950/RetroZilla/blob/master/security/manager/ssl/src/Makefile.in#L134

and before running application, run these to set environment variable for logging:
````
SET NSPR_LOG_MODULES=pipnss:9
SET NSPR_LOG_FILE=c:\projects\moz95\runtimeLog.txt
````

**Comment by rn10950** [comment]
Got the runtime log and inspected it. Doesn't seem to have much NSS stuff in it, let alone errors: https://pastebin.com/WhALkaLv

This is what CMD outputted during the same run:
https://pastebin.com/7RRNiXcR

**Comment by roytam1** [comment]
did you set NSPR_LOG_MODULES and NSPR_LOG_FILE environment variable?

**Comment by rn10950** [comment]
Yes

**Comment by rn10950** [comment]
I have made some changes into the browser code (rebranding Firefox to RetroZilla) and in doing so, I made an interesting discovery: for some reason, only my first Firefox build worked, all later ones failed. I think it may have to do something with my build configuration. If you don't mind, could you post your mozconfig and all configuration information you could give me? (mozbuild version, compiler version, any modifications you made to these, etc). Could you try building suite off of your master or my v2.2 and send me the binaries? I have made all other changes to 2.2 and will ship once this issue is sorted out.

**Comment by rn10950** [comment]
For clarification: worked means the certs loaded, failed means that the cert issue persists. All other aspects of the build went fine. Re-read my previous comment and realized that it wasn't clear.

**Comment by roytam1** [comment]
mozconfig doesn't come in handy right now, have to check when I back to home after work.

and I'm not using mozbuild, but using old cygwin-1.5 as build environment.
compiler version: VC6 with SP5 and VCPP.

and the only non-committed changes is the branding, which should not be an issue for cert IMHO.

**Comment by roytam1** [comment]
just forget about:buildconfig :

--target=i586-pc-msvc --with-branding=myfox --enable-application=browser --enable-single-profile --enable-crypto --enable-canvas --enable-svg --enable-svg-renderer=cairo --enable-necko-small-buffers --enable-optimize --enable-extensions=cookie,xml-rpc,xmlextras,p3p,pref,transformiix,universalchardet,webservices,gnomevfs,cview,auth,permissions,schema-validation,spellcheck,sql --enable-strip-libs --enable-strip --enable-static --disable-shared --disable-debug --disable-dtd-debug --disable-tests --disable-activex --disable-activex-scripting --disable-gtktest --disable-freetype2 --disable-freetypetest --disable-glibtest --disable-libIDLtest --disable-xterm-updates --disable-logging --disable-toolkit-gtk --disable-toolkit-qt --disable-toolkit-xlib --disable-xprint --disable-profilesharing --disable-accessibility --disable-installer --disable-mailnews --disable-composer --disable-postscript --disable-pedantic --disable-irc --disable-cpp-rtti --disable-auto-deps --disable-places --disable-updater

**Comment by rn10950** [comment]
I am setting up a cygwin 1.5 install right now, do you have a Windows SDK installed or do you just build with MSVC6? If so, what SDK?

**Comment by roytam1** [comment]
I used bundled SDK only IIRC, have to check when I back to home.

**Comment by roytam1** [comment]
> do you have a Windows SDK installed

checked and it has SDK 7.1 installed, but NOT used. (and yes it is for palemoon26 vc8 build, again)
and now I tried to compile v2.2 branch (suite build), and just found 1 makefile build, and a PR is issued.

and NSS 3.15.5 seems working fine here, bin: http://o.rthost.cf/gpc/files1.rt/rz-suite-v2.2-bin-20180708.7z

and .mozconfig (it is almost the same as supplied suite mozconfig):

````
GLIB_PREFIX=C:/rz_v22/moztools
LIBIDL_PREFIX=C:/rz_v22/moztools

export MOZ_OPTIMIZE_LDFLAGS="-opt:win98 -LIBPATH:C:/rz_v22/moztools/lib"
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-suite-@CONFIG_GUESS@
mk_add_options OBJDIR=@TOPSRCDIR@/obj-suite-@CONFIG_GUESS@
mk_add_options MOZ_OPTIMIZE_LDFLAGS="-opt:win98 -LIBPATH:C:/rz_v22/moztools/lib"
mk_add_options MOZ_MAKE_FLAGS=-j4

ac_add_options --target=i586-pc-msvc
ac_add_options --enable-application=suite
ac_add_options --enable-optimize
ac_add_options --disable-debug
ac_add_options --disable-tests
ac_add_options --without-system-jpg
ac_add_options --without-system-zlib
ac_add_options --enable-extensions=default,tasks
ac_add_options --enable-crypto
ac_add_options --enable-svg
ac_add_options --enable-canvas

ac_add_options --disable-updater
````

**Comment by roytam1** [comment]
Since mozilla cvs server had been decommissioned, I converted its cvs repo into git with cvs2git-2.5.0.
Unlike other mozilla-cvs-history repos floating around the web which have just only master branch, all branches and tags are uploaded as well.
https://github.com/roytam1/mozilla-cvs-history

**Comment by roytam1** [comment]
> link is down

please change rthost.cf to rths.cf in the link

**Comment by rn10950** [comment]
> 
> 
> > do you have a Windows SDK installed
> 
> checked and it has SDK 7.1 installed, but NOT used. (and yes it is for palemoon26 vc8 build, again)
> and now I tried to compile v2.2 branch (suite build), and just found 1 makefile bug while building, and a PR is issued.
> 
> and NSS 3.15.5 seems working fine here, bin: http://o.rthost.cf/gpc/files1.rt/rz-suite-v2.2-bin-20180708.7z
> 
> and .mozconfig (it is almost the same as supplied suite mozconfig):
> 
> ```
> GLIB_PREFIX=C:/rz_v22/moztools
> LIBIDL_PREFIX=C:/rz_v22/moztools
> 
> export MOZ_OPTIMIZE_LDFLAGS="-opt:win98 -LIBPATH:C:/rz_v22/moztools/lib"
> mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-suite-@CONFIG_GUESS@
> mk_add_options OBJDIR=@TOPSRCDIR@/obj-suite-@CONFIG_GUESS@
> mk_add_options MOZ_OPTIMIZE_LDFLAGS="-opt:win98 -LIBPATH:C:/rz_v22/moztools/lib"
> mk_add_options MOZ_MAKE_FLAGS=-j4
> 
> ac_add_options --target=i586-pc-msvc
> ac_add_options --enable-application=suite
> ac_add_options --enable-optimize
> ac_add_options --disable-debug
> ac_add_options --disable-tests
> ac_add_options --without-system-jpg
> ac_add_options --without-system-zlib
> ac_add_options --enable-extensions=default,tasks
> ac_add_options --enable-crypto
> ac_add_options --enable-svg
> ac_add_options --enable-canvas
> 
> ac_add_options --disable-updater
> ```

I tried your binary for the suite and the cert issue persists. I'm thinking the issue lies in the suite code, but IDK where. I will look through the commit to see if any files in browser/ were modified that also have to be modified on the suite side. The main issue I'm having with that right now is I can't get GitHub to display all the files modified in a commit without hiding files. (I *still* can't get Cygwin to work, so I think I'm just going to stay with mozilla-build and hope for the best)

**Comment by roytam1** [comment]
> I tried your binary for the suite and the cert issue persists.

I wonder if you tried it in new profile?

**Comment by rn10950** [comment]
I looked into the cert issue more, and it appears it was introduced between 1.0 and 1.1. I looked at the compare from 1.0 and 1.1 and nothing in there seems of relativity to a certificate issue. This sounds completely unrelated, but could the app name/profile directory have something to do with certs not working?

Here's the compare:
https://github.com/rn10950/RetroZilla/compare/27b50804da843794f71b1ae3deb7baffccc5a615...e85fc69f9a109af76f4214488dc8ba3fccd26cda

**Comment by rn10950** [comment]
> 
> 
> > I tried your binary for the suite and the cert issue persists.
> 
> I wonder if you tried it in new profile?

Yes, multiple.

**Comment by rn10950** [comment]
Hmm.... seems to work on creation of new profile, but fail the second time. I'm going to run a clean build and try it out again.

**Comment by rn10950** [comment]
I can now confirm that the certificate issue was introduced between 1.0 and 1.1. I did fresh builds of both releases using the GitHub source for each release, with the same mozconfig, on a freshly installed VC6/Mozilla Build 1.2/WinXP environment.

The issue is somewhere in [here](https://github.com/rn10950/RetroZilla/compare/27b50804da843794f71b1ae3deb7baffccc5a615...e85fc69f9a109af76f4214488dc8ba3fccd26cda), just don't know what in here could possibly break the certificate store. I'm leaning in the direction of the profile dir/app name change, but IDK how that would break certificates.

**Comment by roytam1** [comment]
for branding changes, `configure.in` side is not changed. And also there is some hidden places need to be changed like: https://github.com/rn10950/RetroZilla/blob/cc3fbb8f086483feaf9f82abb03c29f25f168362/xpcom/io/nsAppFileLocationProvider.cpp#L87

**Comment by rn10950** [comment]
I changed all of the hardcoded "mozilla" strings that I could find that look relevant to the profile directory using WinXP's text search and DXR, still doesn't work. I think I may ask around on IRC to see if they may pick up on something we didn't.

**Comment by rn10950** [comment]
It's not the profile directory. I ran a test build with the original profile directory restored, still getting that cert issue. I'm officially stumped now.  I don't see one other thing that could have changed between the two releases that could have caused this.

**Comment by rn10950** [comment]
It turns out the certificate issue was being caused by git bash being installed on the same machine as the build system. I found a way (albeit a long and convoluted one) to release builds without this issue, so therefore, I can mark TLS 1.2 support as fixed.
